server:
  servlet:
    context-path: /api/v1

spring:
  application:
    name: fintech-transaction-api
  web:
    error:
      include-message: never
      include-stacktrace: never
      include-exception: false

logging:
  level:
    root: INFO

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
